# Generated by Django 3.0.2 on 2020-02-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades_ex', models.PositiveIntegerField(help_text='Ingrese las unidades del producto', verbose_name='Unidades Existentes:')),
                ('id_producto', models.ForeignKey(help_text='Ingrese el nombre del producto', on_delete=django.db.models.deletion.CASCADE, to='supermercado.Producto', verbose_name='Producto:')),
                ('id_sucursal', models.ForeignKey(help_text='Ingrese el nombre de la sucursal', on_delete=django.db.models.deletion.CASCADE, to='supermercado.Sucursales', verbose_name='Sucursal:')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'unique_together': {('id_sucursal', 'id_producto')},
            },
        ),
    ]
