# Generated by Django 3.0.2 on 2020-02-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0007_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
