# Generated by Django 3.0.2 on 2020-02-29 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supermercado', '0008_delete_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(help_text='Ingrese la fecha de nacimiento', verbose_name='Fecha Nacimiento:')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indefinido')], default='I', help_text='Ingrese su sexo', max_length=1, verbose_name='Sexo:')),
                ('cedula', models.CharField(blank=True, help_text='Ingrese su numero de cedula', max_length=20, verbose_name='Cedula:')),
                ('telefono', models.CharField(blank=True, help_text='Inglese telefono', max_length=20, verbose_name='Telefono:')),
                ('id_usuario', models.ForeignKey(help_text='Ingrese el usuario', on_delete=django.db.models.deletion.CASCADE, related_name='userdetails_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario:')),
            ],
            options={
                'verbose_name': 'Detalles Usuario',
                'verbose_name_plural': 'Detalles Usuarios',
            },
        ),
        migrations.CreateModel(
            name='DetailsCarrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Inglese la cantidad de productos', verbose_name='Cantidad:')),
                ('status', models.CharField(choices=[('C', 'Carrito'), ('P', 'Pedido')], default='C', help_text='Ingrese el estado del prodcuto', max_length=1, verbose_name='Status:')),
                ('id_inventario', models.ForeignKey(help_text='Ingrese inventario que decea agregar al carrito', on_delete=django.db.models.deletion.CASCADE, related_name='detailscarrito_inventario', to='supermercado.Inventario', verbose_name='Inventario:')),
                ('id_pedido', models.ForeignKey(blank=True, help_text='Ingrese el pedido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailscarrito_pedido', to='supermercado.Pedido', verbose_name='Pedido:')),
                ('id_usuario', models.ForeignKey(help_text='Ingrese el usuario', on_delete=django.db.models.deletion.CASCADE, related_name='detailscarrito_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario:')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
    ]
