# Generated by Django 3.0.2 on 2020-03-01 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0013_auto_20200301_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(default=1, help_text='Ingrese la categoria del producto', on_delete=django.db.models.deletion.CASCADE, related_name='producto_categoria', to='supermercado.Categoria', verbose_name='Categoria Producto:'),
            preserve_default=False,
        ),
    ]
