# Generated by Django 3.0.2 on 2020-03-04 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supermercado', '0014_auto_20200301_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='id_usuario',
            field=models.ForeignKey(help_text='Ingrese el usuario', on_delete=django.db.models.deletion.CASCADE, related_name='userdetails_usuario', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Usuario:'),
        ),
    ]
