# Generated by Django 3.0.2 on 2020-03-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermercado', '0015_auto_20200304_1854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailscarrito',
            unique_together={('id_inventario', 'id_pedido')},
        ),
    ]
